### ISSUE TITLE
Apps without banner notifications don't show badges 

### ISSUE THREAD

**Issue by xiaoniuniuyyds** [waresnew/badgesync#2]
https://github.com/user-attachments/assets/9a0f1609-c301-47ee-a8d4-3b51f0c02146

**Describe the bug**
Please describe what the bug is.

**To Reproduce**

*For example:*
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error

**Expected behavior**

**Screen Recording/Screenshots**
If applicable, add a screen recording or screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Jailbreak [e.g. Dopamine, palera1n]

**Additional context**

**Comment by xiaoniuniuyyds** [comment]
https://github.com/user-attachments/assets/3324fbc9-ef97-4ce4-9624-77e185404fb8

**Comment by waresnew** [comment]
Ohh, that makes sense. Sorry about that. I just fixed it and will include it in 1.1.2.

Thanks for letting me know about these issues!
